<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'PayPal' => [$vendorDir . '/paypal/rest-api-sdk-php/lib'],
];
